server.port=8085
spring.application.name=auth-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/campusconnect_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:campusconnect}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password123}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
