server.port=8088
spring.application.name=notification-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/campusconnect_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:campusconnect}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password123}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
